### ISSUE TITLE
Multi-node GA Reqs

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#7538]
This is the meta issue tracking everything that needs to happen to get our multi-node feature more stable and no longer experimental.

- [ ] Multi-node should survive restarts (#7496)
- [ ] Integration tests (#7462) 
- [ ] Automated CNI at run time (#7459)
- [ ] Multi control plane clusters (#7461) 
- [ ] `minikube node start/add` should respect relevant `minikube start` parameters (#7366)
- [ ] `minikube profile` commands need to not be broken (#6780) 
- [ ] docker-env (#6506) 

Once this issue is closed, we should be good to close #94 

Please add any other relevant issues that I might have missed.

**Comment by priyawadhwa** [comment]
still in progress :)

**Comment by danmutblix** [comment]
An absolutely feat! ❤
