### ISSUE TITLE
identify all minikube tech debt for Q4

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9138]
- [ ] iso push after deploy/ISO PR  merges (test against a pushed merged ISO on head)
- [ ] kic base image push after delpoy/kic-base/Dockerfile PR merge to image repositories (gcr, docker hub, ...)
- [ ] storage provisioner and gvisor image push on merge
- [ ] health check Azure Windows VMs (including provision, keep alive, install tools) 
- [ ] identify debian 9 vs debian 10 integration test differences. (weird results on debian 10)
- [ ] PR Bot to auto Comment on the PR the flake rate for each test similar to https://github.com/kubernetes/minikube/issues/9073#issuecomment-684060703 (using Thomas' script on jenkins)
- [ ] bump preload version when we change aux example image https://github.com/kubernetes/minikube/pull/9159/files
- [ ] Ensure Gh Action tests get triggered by go.mod changes https://github.com/kubernetes/minikube/pull/9160
- [ ] Make do-not-sleep run on windows machine as a service
- [ ] Add Stress Test to Jenkins
- [x] HTML report for integration test in Makefile https://github.com/kubernetes/minikube/issues/9212
- [ ] update kuberntes docs minikube installation https://kubernetes.io/docs/tasks/tools/install-minikube/
- [ ] Figure out the docker desktop File Sharing Notification.
- [ ] Brew PR opener in jenkins run in docker https://github.com/kubernetes/minikube/issues/7036
- [] ok to test be required for gh action

**Comment by afbjorklund** [comment]
* The "minikube version" says the code was dirty when it was built
* Now "minikube start" for v0.0.13 uses kicbase:v0.0.12-snapshot3
